### ISSUE TITLE
Melhoria de arquitetura

### ISSUE THREAD

**Issue by brunoruas2** [leovnoliveira/get_data_cvm#2]
![image](https://github.com/user-attachments/assets/8c6e1ad3-a7a5-4754-bbdc-4a61acf8c1f6)

Pega essa seção que executa tua main class e joga pra pasta raiz do repo com o nome Main.py pra segregar o que é arquivo da classe e o que é o script principal.

**Comment by leovnoliveira** [comment]
Refatoração realizada conforme solicitado! A execução principal foi movida para Main.py na pasta main, e as classes e métodos foram organizados na pasta scripts. Obrigado pela sugestão! 😄
